
export const GET_SUPPLIER_CARDS: "GET_SUPPLIER_CARDS" = "GET_SUPPLIER_CARDS";
export const GET_SUPPLIER_CARDS_DETAILS: "GET_SUPPLIER_CARDS_DETAILS" = "GET_SUPPLIER_CARDS_DETAILS";
export const GET_SUPPLIER_CARDS_PHOTO: "GET_SUPPLIER_CARDS_PHOTO" = "GET_SUPPLIER_CARDS_PHOTO";
